# Housing Market

### Introduction:

This time we will create our own dataset with fictional numbers to describe a house market. As we are going to create random data don't try to reason of the numbers.

### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Create 3 differents Series, each of length 100, as follows:
1. The first a random number from 1 to 4
2. The second a random number from 1 to 3
3. The third a random number from 10,000 to 30,000

In [2]:
s1 = pd.Series(np.random.randint(1, 5, size=100))
s2 = pd.Series(np.random.randint(1, 4, size=100))
s3 = pd.Series(np.random.randint(10000, 30001, size=100))

### Step 3. Let's create a DataFrame by joinning the Series by column

In [3]:
housemkt = pd.concat([s1, s2, s3], axis=1)

housemkt.head()

   0  1      2
0  1  1  29358
1  3  2  19588
2  3  1  14100
3  3  1  15559
4  3  3  14126

### Step 4. Change the name of the columns to bedrs, bathrs, price_sqr_meter

In [12]:
housemkt = housemkt.rename(columns={0: 'bedrs', 1: 'bathrs', 2: 'price_sqr_meter'})

In [13]:
housemkt

    bedrs  bathrs  price_sqr_meter
0       1       1            29358
1       3       2            19588
2       3       1            14100
3       3       1            15559
4       3       3            14126
..    ...     ...              ...
95      2       3            24244
96      2       2            29672
97      4       2            25566
98      1       2            24915
99      4       2            24474

[100 rows x 3 columns]

### Step 5. Create a one column DataFrame with the values of the 3 Series and assign it to 'bigcolumn'

In [28]:
# join concat the values
bigcolumn = pd.concat([s1, s2, s3], axis=0)

# it is still a Series, so we need to transform it to a DataFrame
bigcolumn = bigcolumn.to_frame()
print(type(bigcolumn))

bigcolumn

<class 'pandas.core.frame.DataFrame'>

        0
0       1
1       3
2       3
3       3
4       3
..    ...
95  24244
96  29672
97  25566
98  24915
99  24474

[300 rows x 1 columns]

In [29]:
housemkt

    bedrs  bathrs  price_sqr_meter  bigcolumn
0       1       1            29358      29360
1       3       2            19588      19593
2       3       1            14100      14104
3       3       1            15559      15563
4       3       3            14126      14132
..    ...     ...              ...        ...
95      2       3            24244      24249
96      2       2            29672      29676
97      4       2            25566      25572
98      1       2            24915      24918
99      4       2            24474      24480

[100 rows x 4 columns]

### Step 6. Oops, it seems it is going only until index 99. Is it true?

In [31]:
len(housemkt)

100

### Step 7. Reindex the DataFrame so it goes from 0 to 299

In [35]:
bigcolumn.reset_index(drop=True, inplace=True)
bigcolumn

         0
0        1
1        3
2        3
3        3
4        3
..     ...
295  24244
296  29672
297  25566
298  24915
299  24474

[300 rows x 1 columns]

In [36]:
housemkt

    bedrs  bathrs  price_sqr_meter  bigcolumn
0       1       1            29358      29360
1       3       2            19588      19593
2       3       1            14100      14104
3       3       1            15559      15563
4       3       3            14126      14132
..    ...     ...              ...        ...
95      2       3            24244      24249
96      2       2            29672      29676
97      4       2            25566      25572
98      1       2            24915      24918
99      4       2            24474      24480

[100 rows x 4 columns]